### ISSUE TITLE
Calling repo service

### ISSUE THREAD

**Issue by OmerKahani** [argoproj-labs/applicationset#12]
For the git generator #7 it makes sense to use the repo service from argocd.

But how do we want to use it?
1. call it direct, use argocd config map to get the ssh key of the repo
2. call it indirect, call argocd repo command

we would probably need to call argocd to do the initial sync

@alexmt @xianlubird

**Comment by OmerKahani** [comment]
@alexmt

**Comment by xianlubird** [comment]
Maybe. the first way `call it indirect, call argocd repo command` is better,  We can reduce supplement

**Comment by alexmt** [comment]
I'm afraid repo server is missing some APIs required for git generators. I guess we will APIs to list files and retrieve file content. We can these APIs in repo-server but not in `argocd repo` command, so I would suggest to call repo server directly.  This also solves authentication problem since repo server does not require authentication. 


I've used this approach in argocd-notifications and it worked pretty well:

https://github.com/argoproj-labs/argocd-notifications/blob/4275eb9a4ebf30892b0452b4a82e9d24c0422196/shared/argocd/service.go

```golang
func (svc *argoCDService) GetCommitMetadata(ctx context.Context, repoURL string, commitSHA string) (*shared.CommitMetadata, error) {
	argocdDB := db.NewDB(svc.namespace, svc.settingsMgr, svc.clientset)
	repo, err := argocdDB.GetRepository(ctx, repoURL)
	if err != nil {
		return nil, err
	}
	metadata, err := svc.repoServerClient.GetRevisionMetadata(ctx, &apiclient.RepoServerRevisionMetadataRequest{
		Repo:     repo,
		Revision: commitSHA,
	})
	if err != nil {
		return nil, err
	}
	return &shared.CommitMetadata{
		Message: metadata.Message,
		Author:  metadata.Author,
		Date:    metadata.Date.Time,
		Tags:    metadata.Tags,
	}, nil
}

```

what do you think @OmerKahani , @xianlubird ?

**Comment by xianlubird** [comment]
Agree with @alexmt

**Comment by OmerKahani** [comment]
@alexec does this mean that the application set controller is using the argocd config map?
