### ISSUE TITLE
[applicationset] applicationsets.argoproj.io "shortNames" value 

### ISSUE THREAD

**Issue by jeff51419** [argoproj-labs/applicationset#208]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I tried to used the argocd-applicationset on argo-cd cluster for deployment.
After I applied the "argocd-applicationset" yaml, RepeatedResourceWarning appeared.

it seems it will modify "applicationsets.argoproj.io" crd.
![image](https://user-images.githubusercontent.com/18411883/115652508-fbffd480-a35f-11eb-86b9-fdc02f6d7cf8.png)

If I try to use kustomize to deploy argocd-applicationset to can avoid they modify the same file.

![image](https://user-images.githubusercontent.com/18411883/115658084-ab41a900-a36a-11eb-8ebd-ff8415138df7.png)

but there is no shortNames in applicationsets.argoproj.io on https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml 

Which version applicationsets.argoproj.io should i use, with shortNames or without shorNames?

**To Reproduce**
1. helm install argocd argo/argo-cd -n argocd --create-namespace
2. argocd proj create -f stp-devops.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stp-devops
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://argoproj.github.io/argo-helm'

    
3. argocd app create -f argocd-applicationset.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationset
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 0.1.2
    chart: argocd-applicationset
  project: stp-devops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true  

**Expected behavior**

argocd-applicationset application without warning message

**Screenshots**

![image](https://user-images.githubusercontent.com/18411883/115539868-12f6e600-a2d0-11eb-9339-cf909a0d0564.png)

**Version**

```shell
argocd: v1.8.7+eb3d1fb.dirty
  BuildDate: 2021-03-07T20:25:24Z
  GitCommit: eb3d1fb84b9b77cdffd70b14c4f949f1c64a9416
  GitTreeState: dirty
  GoVersion: go1.16
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

**Logs**

```
time="2021-04-21T10:44:11Z" level=info msg="Refreshing app status (comparison expired. reconciledAt: 2021-04-21 10:41:11 +0000 UTC, expiry: 3m0s), level (2)" application=argocd-applicationset
time="2021-04-21T10:44:11Z" level=info msg="Ignore status for CustomResourceDefinitions"
time="2021-04-21T10:44:11Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argocd)" application=argocd-applicationset
time="2021-04-21T10:44:11Z" level=info msg="getRepoObjs stats" application=argocd-applicationset build_options_ms=0 helm_ms=0 plugins_ms=0 repo_ms=0 time_ms=19 unmarshal_ms=19 version_ms=0
time="2021-04-21T10:44:11Z" level=info msg="Update successful" application=argocd-applicationset
time="2021-04-21T10:44:11Z" level=info msg="Reconciliation completed" application=argocd-applicationset dedup_ms=0 dest-name= dest-namespace=argocd dest-server="https://kubernetes.default.svc" diff_ms=9 fields.level=2 git_ms=19 health_ms=0 live_ms=0 settings_ms=0 sync_ms=0 time_ms=46
```

**Comment by jgwest** [comment]
Hi @jeff51419 , great bug report! Thanks for the detailed instructions, I'm able to reproduce as well using the instructions you provided. 

I admit I'm not a Helm expert: the ApplicationSet helm charts are handled by @maruina (and others), and they might have additional suggestions. 

Behind the scenes, it looks like Argo CD calls `helm template` using the `--include-crds` option, which causes the CRDs to be included twice in the output. The actual call that Argo CD uses to generate the K8s manifests is:
`
helm template . --name-template argocd-applicationset --namespace argocd --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions flowcontrol.apiserver.k8s.io/v1beta1 --api-versions helm.cattle.io/v1 --api-versions k3s.cattle.io/v1 --api-versions monitoring.coreos.com/v1 --api-versions argoproj.io/v1alpha1 --api-versions bitnami.com/v1alpha1 --api-versions metrics.k8s.io/v1beta1 --include-crds
`
*(you can see this in the Argo CD Repo Server pod logs if you're curious)*

If you clone the `argo-helm` repo and run that same command from within the applicationset chart directory, you can see that the CustomResourceDefinition *does* appear twice.

I'm not sure what the expected behaviour should be in this case, but as a workaround you should be able to use `installCRDs=false` as a value to the Helm chart in your Argo CD Application above, (which will become eg `--set installCRDs=false` to Helm template), which will cause it to only include one CRD definition.


Re: your question of which version of the application set CRD to use, in general you would probably want to stick with the most recently released version, `0.1.0`, which is the version without short names, until the version WITH short names is released (eg in `v0.2.0`).

**Comment by maruina** [comment]
Hi there :)
Regarding Helm, I think it depends which version you are using to render the chart. If you are using helm3, you should set `installCRDs=false` as we say in the README. This will make helm3 looking into the`crds` directory.

I think the problem with the chart is that we don't have the `shortNames` in the CRD because it's copied from https://raw.githubusercontent.com/argoproj-labs/applicationset/v0.1.0/manifests/install.yaml

@jgwest do you think we can update the CRD here so I can port it to the Helm chart?

**Comment by jgwest** [comment]
@maruina Ah, I didn't realize that was a Helm 3 vs Helm 2 thing, that makes sense, thanks! 

Re: shortNames, I think we should wait for the 0.2.0 release that will contain the shortNames change before we update the CRD in the Helm chart. (It _probably_ wouldn't hurt anything to add it, but I'm wary of cherrypicking it back to an older release... people can type a few more characters in the mean time :smile: )

**Comment by jeff51419** [comment]
thanks for your responses, I should set installCRDs=false. And I will wait for the 0.2.0 release.

Keep on good working
