### ISSUE TITLE
Implement Git Files Discovery

### ISSUE THREAD

**Issue by OmerKahani** [argoproj-labs/applicationset#29]
Implement this example https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml

Relate to #28 

Might requires changes to the repo service

**Comment by rtnpro** [comment]
I want to work on this. However, there's some clarifications I need on this spec before proceeding.

Should we implement the file path filter regex as specified [here](https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml#L44): `**/config.json`? Contrary to the `GitDirectory` generator implementation, the `directory` path filter regex, e.g., `addons/*` is a valid filter working with Golang's `path` library.

But the regex used in the example [here](https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml#L44) won't work as is to filter file paths using the `path` library. Examples

![image](https://user-images.githubusercontent.com/231684/92006033-d8046a00-ed61-11ea-855d-875ebe8c2d32.png)

However, using a pattern like `*/*/*/config.json` works perfectly with `path.Match` for paths specified in the example [here](https://github.com/argoproj-labs/applicationset/blob/master/examples/git-files-discovery.yaml).

![image](https://user-images.githubusercontent.com/231684/92006274-2285e680-ed62-11ea-8cd7-f57ad1b54787.png)

I think that using a valid regex pattern that's directly compatible with `path.Match(...)` rather than coming up with a new non standard pattern like `**/config.json` would make more sense. Also, `*/*/*/config.json` explicitly mentions at which level of the directory tree to look for the `config.json` file.

Thoughts? cc @OmerKahani @dgoodwin @xianlubird

**Comment by OmerKahani** [comment]
I used path.Match in https://github.com/argoproj-labs/applicationset/pull/7

**Comment by rtnpro** [comment]
I have a few more queries.

- Are Git directory generator and Git file generator mutually exclusive? (Seems so to me from the examples)
- What are the allowed patterns/variations for `path` in git file generator? `**/config.json` will force to look for cluster configs in the entire repo. On the other hand, `cluster-configs/**/config.json` would be able limit search for configs to specific paths. What all patterns do we plan to support for `path` for file discovery?

cc @OmerKahani @xianlubird

**Comment by OmerKahani** [comment]
I think we can start with them been mutually exclusive.

About the paths, both examples are good, and we should probably support both. I don't think we can map all the patterns in advance, we should structure the code so adding a new pattern is easy and can be tested with a unit test.
I will recommend starting with one or two patterns, get the PR merged, and then start to think about other patterns.

Hope this is helpful
