### ISSUE TITLE
Unable to set parameter overrides

### ISSUE THREAD

**Issue by voldemortensen** [argoproj-labs/applicationset#339]
On applications created with an ApplicationSet I am unable to set parameter overrides that are persistent. After running
`argocd app set some-app -p some-parameter=new-value` the parameter is set for a few seconds but is removed when the next reconcile runs.

**Comment by jgwest** [comment]
Hi @voldemortensen  , this is due to the way the the ApplicationSet controller manages the individual Applications it creates. For this release, I documented this behaviour and rationale here: https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#limitation-no-support-for-manual-edits-to-individual-applications
