### ISSUE TITLE
Cannot disable Aut-sync for apps made by applicationset controller

### ISSUE THREAD

**Issue by dorroddorrod** [argoproj-labs/applicationset#345]
Hi,
When generating Argo applications using ApplicationSet resource with `spec.template.syncPolicy.automated`, i'm unable to disable the sync policy from the UI or CLI, therefor, i'm not able to make a deployment rollback.

https://user-images.githubusercontent.com/31075689/130076793-2ebc9377-067d-4fd6-9f92-306e8b3bda77.mov

**Comment by jgwest** [comment]
Hi @dorroddorrod , this is due to the way the the ApplicationSet controller manages all the individual Applications it creates. For this release, I documented this behaviour and rationale here: https://argocd-applicationset.readthedocs.io/en/stable/Controlling-Resource-Modification/#limitation-no-support-for-manual-edits-to-individual-applications
